# Generated by Django 2.0.2 on 2018-02-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20180205_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='client_id',
            new_name='active_transaction_id',
        ),
    ]
